### ISSUE TITLE
Time out image polling for self-hosted-e2e-tests check sooner

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/action-self-hosted-e2e-tests#10]
Right now, the timeout for image polling for self-hosted-e2e-tests can take up to 30 minutes before failing. This should be sooner

**Comment by hubertdeng123** [comment]
Need to bump commit sha's in self-hosted, sentry, relay, and snuba

**Comment by chadwhitacre** [comment]
Ready to land this?

**Comment by hubertdeng123** [comment]
Yeah, didn't get to this last week will put up PR's today.

**Comment by hubertdeng123** [comment]
snuba: https://github.com/getsentry/snuba/pull/4073
sentry: https://github.com/getsentry/sentry/pull/47838
relay: https://github.com/getsentry/relay/pull/2062
self-hosted: https://github.com/getsentry/self-hosted/pull/2104
